/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sortingAlgorithm.app;


public class App {
    public static void main(String[] args) {
        int[] argss = new int[args.length];
        boolean isRunning = true;
        for (int i = 0; i < argss.length ; i++) {
            if (isNumeric(args[i])){
                argss[i] = Integer.parseInt(args[i]);
            }else {
                isRunning = false;
                System.out.print("Please enter Integer!");
            }
        }
        if (isRunning){
            Sorter.selectSort(argss);
            Sorter.printArray(argss);
        }
    }
    // Denna metod bör kontrollera om det givna argumentet är heltal och inte en sträng
    public static boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            int d = Integer.parseInt(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

}
